<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESK-1989" name="a2_Profile_Page.B2_LeftBlock" tests="9" failures="1" timestamp="17 Jul 2017 08:43:30 GMT" time="76.947" errors="0">
  <testcase name="b1_ReviewLink" time="3.522" classname="a2_Profile_Page.B2_LeftBlock"/>
  <testcase name="b2_TnClink" time="3.584" classname="a2_Profile_Page.B2_LeftBlock"/>
  <testcase name="b3_GetDirection" time="6.291" classname="a2_Profile_Page.B2_LeftBlock"/>
  <testcase name="b4_WebSiteLink" time="9.497" classname="a2_Profile_Page.B2_LeftBlock"/>
  <testcase name="b5_ReportError" time="10.541" classname="a2_Profile_Page.B2_LeftBlock"/>
  <testcase name="b6_ReportComplaint" time="8.467" classname="a2_Profile_Page.B2_LeftBlock"/>
  <testcase name="b7_PhotoLink" time="5.333" classname="a2_Profile_Page.B2_LeftBlock"/>
  <testcase name="b8_AlsoListed" time="25.352" classname="a2_Profile_Page.B2_LeftBlock">
    <skipped/>
  </testcase> <!-- b8_AlsoListed -->
  <testcase name="b8_AlsoListed" time="4.360" classname="a2_Profile_Page.B2_LeftBlock">
    <failure type="java.lang.AssertionError" message="issue is also list link expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: issue is also list link expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at a2_Profile_Page.B2_LeftBlock.b8_AlsoListed(B2_LeftBlock.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- b8_AlsoListed -->
</testsuite> <!-- a2_Profile_Page.B2_LeftBlock -->
